# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8.0

      # - environment:
      #   PG_USER: root
      #   PG_DATABASE: reviews
      #   PG_PORT: 5432
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run install

      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          command: npm run db:reset:test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
      # - run:
      #     name: Deploy Master to Heroku
      #     command: |
      #       git push https://heroku:$HEROKU_API_KEY@git.heroku.com/cc-demo-test.git master
